In [1]:
import pandas as pd
import numpy as np

In [2]:
trips = pd.read_csv('data/trips.txt')
stops = pd.read_csv('data/stops.txt')
routes = pd.read_csv('data/routes.txt')
stop_times = pd.read_csv('data/stop_times.txt')

In [3]:
trips.describe()

           route_id  service_id       trip_id
count  16562.000000     16562.0  16562.000000
mean     284.504287         1.0   8280.500000
std      159.175796         0.0   4781.181915
min        0.000000         1.0      0.000000
25%      167.000000         1.0   4140.250000
50%      294.000000         1.0   8280.500000
75%      423.000000         1.0  12420.750000
max      542.000000         1.0  16561.000000

In [4]:
trips

       route_id  service_id  trip_id
0             0           1        0
1             0           1        1
2             0           1        2
3             0           1        3
4             0           1        4
5             0           1        5
6             0           1        6
7             0           1        7
8             0           1        8
9             0           1        9
10            0           1       10
11            0           1       11
12            0           1       12
13            0           1       13
14            0           1       14
15            0           1       15
16            0           1       16
17            0           1       17
18            0           1       18
19            0           1       19
20            0           1       20
21            0           1       21
22            0           1       22
23            0           1       23
24            0           1       24
25            0           1       25
26            0           1       26
27            0           1       27
28            0           1       28
29            0           1       29
...         ...         ...      ...
16532       540           1    16532
16533       540           1    16533
16534       541           1    16534
16535       541           1    16535
16536       541           1    16536
16537       541           1    16537
16538       541           1    16538
16539       541           1    16539
16540       541           1    16540
16541       541           1    16541
16542       541           1    16542
16543       541           1    16543
16544       541           1    16544
16545       541           1    16545
16546       541           1    16546
16547       541           1    16547
16548       542           1    16548
16549       542           1    16549
16550       542           1    16550
16551       542           1    16551
16552       542           1    16552
16553       542           1    16553
16554       542           1    16554
16555       542           1    16555
16556       542           1    16556
16557       542           1    16557
16558       542           1    16558
16559       542           1    16559
16560       542           1    16560
16561       542           1    16561

[16562 rows x 3 columns]

In [5]:
routes

     route_short_name                route_long_name  route_type  route_id
0                 NaN                        108DOWN           3         0
1                 NaN                     108STLDOWN           3         1
2                 NaN                       108STLUp           3         2
3                 NaN                          108UP           3         3
4                 NaN                        185DOWN           3         4
5                 NaN                  185LnkSTLDown           3         5
6                 NaN                    185LnkSTLUp           3         6
7                 NaN                     185STLDOWN           3         7
8                 NaN                       185STLUP           3         8
9                 NaN                          185UP           3         9
10                NaN                     234CL_DOWN           3        10
11                NaN                       234CL_UP           3        11
12                NaN                        262DOWN           3        12
13                NaN                 262LinkSTLDown           3        13
14                NaN                   262LinkSTLUP           3        14
15                NaN                          262UP           3        15
16                NaN                         78DOWN           3        16
17                NaN                      78STLDOWN           3        17
18                NaN                        78STLUP           3        18
19                NaN                           78UP           3        19
20                NaN                    7LnkSTLDown           3        20
21                NaN                      7LnkSTLUp           3        21
22                NaN                      813CLDown           3        22
23                NaN                        813CLUP           3        23
24                NaN                  813LnkSTLDown           3        24
25                NaN                    813LnkSTLUp           3        25
26                NaN                       937ADOWN           3        26
27                NaN                         937AUP           3        27
28                NaN                  982LnkSTLDown           3        28
29                NaN                    982LnkSTLUp           3        29
..                ...                            ...         ...       ...
513               NaN                     624ACLDown           3       513
514               NaN                       624ACLUP           3       514
515               NaN                624ALinkSTLDown           3       515
516               NaN                  624ALinkSTLUP           3       516
517               NaN                 624BLnkSTLDown           3       517
518               NaN                   624BLnkSTLUp           3       518
519               NaN                      803CLDown           3       519
520               NaN                        803CLUp           3       520
521               NaN                       805ADown           3       521
522               NaN                         805AUp           3       522
523               NaN                      894CLDown           3       523
524               NaN                        894CLUp           3       524
525               NaN                     894STLDown           3       525
526               NaN                       894STLUp           3       526
527               NaN                         91DOWN           3       527
528               NaN                  91LinkSTLDown           3       528
529               NaN                    91LinkSTLUP           3       529
530               NaN                           91UP           3       530
531               NaN              TMS(+)LajpatNagar           3       531
532               NaN                         TMS+AL           3       532
533               NaN             TMS+Lajpat-Azadpur           3       533
534               NaN             TMS-Azadpur-Lajpat           3       534
535               NaN                TMS-LajpatNagar           3       535
536               NaN  TMS-LajpatNgr-AzadpurTerminal           3       536
537               NaN                        721DOWN           3       537
538               NaN                          721UP           3       538
539               NaN                        727DOWN           3       539
540               NaN                          727UP           3       540
541               NaN                        751Down           3       541
542               NaN                          751Up           3       542

[543 rows x 4 columns]

In [6]:
stops

,stop_id,stop_code,stop_name,stop_lat,stop_lon
0,0,U01761,Adarsh Nagar / Bharola Village,28.715917,77.170867
1,1,DC4248,British High Comission,28.598533,77.191383
2,2,U02398,Azad Market,28.664700,77.208400
3,3,U02416,Kidwai Nagar,28.575700,77.209700
4,4,DC4271,Rashid Market,28.650200,77.278667
5,5,U03074,Nehru Nagar,28.569150,77.253883
6,6,U02904,Sunder Nagar,28.602217,77.240400
7,7,DC4225,Suraj Mal Vihar,28.661283,77.303517
8,8,U02563,National Archives,28.614700,77.218500
9,9,U02922,Darya Ganj,28.646083,77.240400
10,10,U00314,Nangli Sakrawati,28.614667,77.003400
11,11,U01623,B-4 Keshav Puram,28.687550,77.162500
12,12,U99637,Bawana Village,28.801917,77.039067
13,13,U00086,Mitraon Village,28.608213,76.947336
14,14,U03518,Hargovind Enclave,28.645667,77.300467
15,15,U00193,NajafGarh Dhansa Stand,28.611500,76.977817
16,16,U03678,Super Bazar,28.613350,77.316200
17,17,U99639,Kapashera Crossing,28.528867,77.086750
18,18,U03409,Batla House,28.562317,77.286100
19,19,U00429,Karala Village,28.731500,77.037000
20,20,U00786,Manglapuri / Palam Village,28.589317,77.086350
21,21,U02926,Delhi Gate (JLN Marg),28.640024,77.238077
22,22,U00828,Udyog Nagar,28.680300,77.089300
23,23,U01798,Ashok Vihar Water Tank,28.687017,77.173667
24,24,DC4148,Centaur Hotel / New Custom House,28.553099,77.103543
25,25,DC3956,Bhagwan Mahavir Hospital,28.687467,77.118117
26,26,U03522,Badarpur Village,28.502067,77.300033
27,27,U03766,Mayur Vihar Phase 3 Crossing,28.601800,77.327350
28,28,DC4394,Ranhola Extension,28.657906,77.043018
29,29,NS0252,COD Ring Road,28.613000,77.136717
...,...,...,...,...,...
3435,3571,DC3645,Dwarka Flyover / Palam Village,28.583833,77.091417
3436,3572,U01379,Sri Nagesh Garden,28.596550,77.140650
3437,3573,DC4448,Kangan Heri - I,28.548293,76.988737
3438,3574,U03708,Gazi Pur DDA Flats,28.623000,77.319800
3439,3575,DC3911,Sarai Rohilla Flyover,28.667017,77.181867
3440,3576,DC4597,School Of Physical Science,28.546433,77.179250
3441,3577,U04005A,Kirbi Place,28.604833,77.128283
3442,3578,U01594,Golf Club,28.592967,77.158483
3443,3579,U02237RRS,Ravinder Rang Shala,28.640700,77.195100
3444,3580,DC4425,KharKhari Jatmal,28.582168,76.957902
3445,3581,U03091,Indraprastha Park,28.599800,77.254900
3446,3582,DC4574,ISBT Kashmere Gate Terminal,28.667007,77.227510
3447,3583,DC3970,Bijwasan Railway Crossing,28.533117,77.055783
3448,3584,U01392,Kohat Enclave Metro Station,28.697200,77.142100
3449,3585,U01462,ESI Dispensary/CGHS Dispensary,28.660583,77.147367
3450,3586,DC4362,Ibrahim Pur More,28.775793,77.179669
3451,3587,U03122,Ashram (Hari Nagar),28.573817,77.257333
3452,3588,U01696,Bhalaswa Xing,28.737450,77.166617
3453,3589,U02017,State Bank Colony,28.695600,77.187800
3454,3590,U03367,Ansari Health Care,28.560917,77.281183
3455,3591,U02751,Siri Fort Road,28.554683,77.228567
3456,3592,DC4511,Satya Puram Jharoda,28.663282,76.944684
3457,3594,DC0091,Holy Child School,28.650600,77.113900
3458,3595,DC3582,Jagjit Nagar,28.686250,77.254350
3459,3596,U00231,Chawla Stand Najafgarh,28.608400,76.985500
3460,3597,U03375,Samaspur Jagir Village (Pusta Xing),28.615983,77.285350
3461,3598,U00854,Peera Garhi Metro Station,28.679667,77.092833
3462,3599,U02682,Civil Line Metro Station,28.616617,77.225017
3463,3600,DC4660,Sabhapur Crossing,28.729133,77.259700
3464,3601,DC4119,Lalita Park,28.632050,77.270900

In [7]:
stop_times

        trip_id arrival_time departure_time  stop_id  stop_sequence
0             0     15:48:00       15:48:00     2270              0
1             0     15:49:52       15:49:52      978              1
2             0     15:52:17       15:52:17     3005              2
3             0     15:54:02       15:54:02      255              3
4             0     15:56:47       15:56:47     3074              4
5             0     15:59:32       15:59:32      764              5
6             0     16:02:49       16:02:49      619              6
7             0     16:04:22       16:04:22     1973              7
8             0     16:07:54       16:07:54     2502              8
9             0     16:14:25       16:14:25     2871              9
10            0     16:17:29       16:17:29     3039             10
11            0     16:20:53       16:20:53     1462             11
12            0     16:24:01       16:24:01      731             12
13            0     16:26:04       16:26:04     1837             13
14            0     16:28:15       16:28:15     3585             14
15            0     16:32:08       16:32:08     3425             15
16            0     16:36:17       16:36:17     3227             16
17            0     16:39:23       16:39:23      949             17
18            0     16:42:13       16:42:13      953             18
19            0     16:45:45       16:45:45     3092             19
20            0     16:47:35       16:47:35      803             20
21            0     16:50:30       16:50:30     1416             21
22            0     16:52:20       16:52:20     2768             22
23            0     16:54:13       16:54:13     3034             23
24            0     16:55:59       16:55:59      733             24
25            0     16:57:20       16:57:20      703             25
26            0     17:02:11       17:02:11      580             26
27            0     17:06:37       17:06:37     3156             27
28            0     17:07:33       17:07:33     2142             28
29            0     17:09:05       17:09:05     3451             29
...         ...          ...            ...      ...            ...
674879    16561     11:34:16       11:34:16     3504             28
674880    16561     11:34:18       11:34:18     1490             29
674881    16561     11:36:25       11:36:25      188             30
674882    16561     11:38:42       11:38:42     1814             31
674883    16561     11:40:44       11:40:44      948             32
674884    16561     11:43:35       11:43:35     1661             33
674885    16561     11:46:26       11:46:26     1381             34
674886    16561     11:51:45       11:51:45     3139             35
674887    16561     11:51:47       11:51:47     1452             36
674888    16561     11:54:29       11:54:29     2758             37
674889    16561     11:56:33       11:56:33      109             38
674890    16561     12:01:48       12:01:48     3456             40
674891    16561     12:03:43       12:03:43     1930             41
674892    16561     12:05:34       12:05:34     1090             42
674893    16561     12:08:49       12:08:49     3096             43
674894    16561     12:10:52       12:10:52     1857             44
674895    16561     12:13:31       12:13:31     3164             45
674896    16561     12:14:57       12:14:57     2410             46
674897    16561     12:18:17       12:18:17     1105             47
674898    16561     12:20:59       12:20:59     3406             48
674899    16561     13:10:33       13:10:33      560             49
674900    16561     13:56:31       13:56:31     2333             50
674901    16561     13:59:44       13:59:44     3145             51
674902    16561     14:01:53       14:01:53     1969             52
674903    16561     14:03:12       14:03:12      251             53
674904    16561     14:04:43       14:04:43     2689             54
674905    16561     14:06:34       14:06:34      566             55
674906    16561     14:08:09       14:08:09     2986             56
674907    16561     14:12:11       14:12:11     1151             57
674908    16561     14:15:43       14:15:43     3130             58

[674909 rows x 5 columns]

In [8]:
a = stop_times['arrival_time']==stop_times['departure_time']

In [9]:
#in consideration: let stop name: BRITISH HIGH COMISSION

In [10]:
def find_route_ids(name):
    ele = stops.loc[stops['stop_name']==name]
    step3 = pd.DataFrame()
    ele = ele.iloc[0]
    step_2 = stop_times.loc[stop_times['stop_id']==int(ele['stop_id'])]
    
    for i in step_2['trip_id']:
        b = trips.loc[trips['trip_id']==i]
        a = np.asarray(b)
        step3 = step3.append(b)
    to_comp = np.unique(np.asarray(step3['route_id']))
    step4 = pd.DataFrame()
    for rid in to_comp:
        c = routes.loc[routes['route_id'] ==rid]
        step4 = step4.append(c)
    source_route_id = np.asarray(step4['route_id'])
    
    return source_route_id, np.asarray(step4['route_long_name'])

In [11]:
def check_zero_hop(source, dest):
    ch = set(find_route_ids(source)[0]).intersection(set(find_route_ids(dest)[0])) 
    return bool(ch)

In [12]:
check_zero_hop('Hasanpur Depot', 'Hari Nagar Ghanta Ghar')

False

In [13]:
ele = stops.loc[stops['stop_name']=='Hasanpur Depot']

In [14]:
ele['stop_id']

280    280
Name: stop_id, dtype: int64

In [15]:
#34- 280

In [16]:
step_2 = stop_times.loc[stop_times['stop_id']==int(ele['stop_id'])]

In [17]:
step_2

        trip_id arrival_time departure_time  stop_id  stop_sequence
38033      1120     15:11:55       15:11:55      280             18
38076      1121     14:23:55       14:23:55      280             18
38119      1122     16:07:55       16:07:55      280             18
38162      1123     14:07:55       14:07:55      280             18
38205      1124     14:55:55       14:55:55      280             18
38248      1125     15:51:55       15:51:55      280             18
38291      1126     14:39:55       14:39:55      280             18
38334      1127     17:37:55       17:37:55      280             18
38377      1128     17:45:55       17:45:55      280             18
38420      1129     18:49:55       18:49:55      280             18
38463      1130     07:37:55       07:37:55      280             18
38506      1131     09:37:55       09:37:55      280             18
38549      1132     16:57:55       16:57:55      280             18
38592      1133     07:53:55       07:53:55      280             18
38635      1134     08:25:55       08:25:55      280             18
38678      1135     08:41:55       08:41:55      280             18
38721      1136     08:09:55       08:09:55      280             18
38764      1137     09:13:55       09:13:55      280             18
38807      1138     19:05:55       19:05:55      280             18
38850      1139     17:13:55       17:13:55      280             18
38893      1140     18:17:55       18:17:55      280             18
38936      1141     12:09:55       12:09:55      280             18
38979      1142     21:37:55       21:37:55      280             18
39022      1143     11:05:55       11:05:55      280             18
39065      1144     20:25:55       20:25:55      280             18
39108      1145     22:25:55       22:25:55      280             18
39151      1146     10:49:55       10:49:55      280             18
39194      1147     11:37:55       11:37:55      280             18
39237      1148     12:49:55       12:49:55      280             18
39280      1149     11:21:55       11:21:55      280             18
...         ...          ...            ...      ...            ...
626736    15505     10:09:40       10:09:40      280              5
626785    15506     19:29:40       19:29:40      280              5
626834    15507     20:33:40       20:33:40      280              5
626883    15508     11:45:40       11:45:40      280              5
626932    15509     10:41:40       10:41:40      280              5
626981    15510     22:01:40       22:01:40      280              5
627030    15511     12:17:40       12:17:40      280              5
627079    15512     18:57:40       18:57:40      280              5
627128    15513     22:17:40       22:17:40      280              5
627177    15514     12:49:40       12:49:40      280              5
627226    15515     11:13:40       11:13:40      280              5
627275    15516     09:37:40       09:37:40      280              5
627324    15517     20:01:40       20:01:40      280              5
627373    15518     21:37:40       21:37:40      280              5
627422    15519     14:09:40       14:09:40      280              5
627471    15520     12:33:40       12:33:40      280              5
627520    15521     13:37:40       13:37:40      280              5
627569    15522     14:33:40       14:33:40      280              5
627618    15523     14:41:40       14:41:40      280              5
627667    15524     13:05:40       13:05:40      280              5
627716    15525     12:01:40       12:01:40      280              5
627765    15526     14:49:40       14:49:40      280              5
627814    15527     11:29:40       11:29:40      280              5
631576    15617     22:53:40       22:53:40      280              5
631610    15618     21:17:40       21:17:40      280              5
631644    15619     20:45:40       20:45:40      280              5
631678    15620     22:21:40       22:21:40      280              5
631712    15621     20:13:40       20:13:40      280              5
631746    15622     23:23:40       23:23:40      280              5
631780    15623     21:49:40       21:49:40      280              5

[908 rows x 5 columns]

In [18]:
step3 = pd.DataFrame()
j=0
for i in step_2['trip_id']:
    b = trips.loc[trips['trip_id']==i]
    a = np.asarray(b)
    #step3.append(np.asarray(trips.loc[trips['trip_id']==i]))
    step3 = step3.append(b)
    print("  ",b, " ",j)
    j+=1

         route_id  service_id  trip_id
1120        34           1     1120   0
         route_id  service_id  trip_id
1121        34           1     1121   1
         route_id  service_id  trip_id
1122        34           1     1122   2
         route_id  service_id  trip_id
1123        34           1     1123   3
         route_id  service_id  trip_id
1124        34           1     1124   4
         route_id  service_id  trip_id
1125        34           1     1125   5
         route_id  service_id  trip_id
1126        34           1     1126   6
         route_id  service_id  trip_id
1127        34           1     1127   7
         route_id  service_id  trip_id
1128        34           1     1128   8
         route_id  service_id  trip_id
1129        34           1     1129   9
         route_id  service_id  trip_id
1130        34           1     1130   10
         route_id  service_id  trip_id
1131        34           1     1131   11
         route_id  service_id  trip_id
1132        34           1     1132   12
         route_id  service_id  trip_id
1133        34           1     1133   13
         route_id  service_id  trip_id
1134        34           1     1134   14
         route_id  service_id  trip_id
1135        34           1     1135   15
         route_id  service_id  trip_id
1136        34           1     1136   16
         route_id  service_id  trip_id
1137        34           1     1137   17
         route_id  service_id  trip_id
1138        34           1     1138   18
         route_id  service_id  trip_id
1139        34           1     1139   19
         route_id  service_id  trip_id
1140        34           1     1140   20
         route_id  service_id  trip_id
1141        34           1     1141   21
         route_id  service_id  trip_id
1142        34           1     1142   22
         route_id  service_id  trip_id
1143        34           1     1143   23
         route_id  service_id  trip_id
1144        34           1     1144   24
         route_id  service_id  trip_id
1145        34           1     1145   25
         route_id  service_id  trip_id
1146        34           1     1146   26
         route_id  service_id  trip_id
1147        34           1     1147   27
         route_id  service_id  trip_id
1148        34           1     1148   28
         route_id  service_id  trip_id
1149        34           1     1149   29
         route_id  service_id  trip_id
1150        34           1     1150   30
         route_id  service_id  trip_id
1151        34           1     1151   31
         route_id  service_id  trip_id
1152        34           1     1152   32
         route_id  service_id  trip_id
1153        34           1     1153   33
         route_id  service_id  trip_id
1154        34           1     1154   34
         route_id  service_id  trip_id
1190        36           1     1190   35
         route_id  service_id  trip_id
1191        36           1     1191   36
         route_id  service_id  trip_id
1192        36           1     1192   37
         route_id  service_id  trip_id
1193        36           1     1193   38
         route_id  service_id  trip_id
1194        36           1     1194   39
         route_id  service_id  trip_id
1195        36           1     1195   40
         route_id  service_id  trip_id
1196        36           1     1196   41
         route_id  service_id  trip_id
1197        36           1     1197   42
         route_id  service_id  trip_id
1198        36           1     1198   43
         route_id  service_id  trip_id
1199        36           1     1199   44
         route_id  service_id  trip_id
1200        36           1     1200   45
         route_id  service_id  trip_id
1201        36           1     1201   46
         route_id  service_id  trip_id
1202        36           1     1202   47
         route_id  service_id  trip_id
1203        36           1     1203   48
         route_id  service_id  trip_id
1204        36           1     1204   49
         route_id  service_id  trip_id
1205        36           1     1205   50
         route_id  service_id  trip_id
1206        36           1     1206   51
         route_id  service_id  trip_id
1207        36           1     1207   52
         route_id  service_id  trip_id
1208        36           1     1208   53
         route_id  service_id  trip_id
1209        36           1     1209   54
         route_id  service_id  trip_id
1210        36           1     1210   55
         route_id  service_id  trip_id
1211        36           1     1211   56
         route_id  service_id  trip_id
1212        36           1     1212   57
         route_id  service_id  trip_id
1213        36           1     1213   58
         route_id  service_id  trip_id
1214        36           1     1214   59
         route_id  service_id  trip_id
1215        36           1     1215   60
         route_id  service_id  trip_id
1216        36           1     1216   61
         route_id  service_id  trip_id
1217        36           1     1217   62
         route_id  service_id  trip_id
1218        36           1     1218   63
         route_id  service_id  trip_id
1219        36           1     1219   64
         route_id  service_id  trip_id
1220        36           1     1220   65
         route_id  service_id  trip_id
1221        36           1     1221   66
         route_id  service_id  trip_id
1222        36           1     1222   67
         route_id  service_id  trip_id
1223        36           1     1223   68
         route_id  service_id  trip_id
1224        36           1     1224   69
         route_id  service_id  trip_id
1225        36           1     1225   70
         route_id  service_id  trip_id
1226        36           1     1226   71
         route_id  service_id  trip_id
1227        36           1     1227   72
         route_id  service_id  trip_id
1228        36           1     1228   73
         route_id  service_id  trip_id
1229        36           1     1229   74
         route_id  service_id  trip_id
1230        36           1     1230   75
         route_id  service_id  trip_id
1231        36           1     1231   76
         route_id  service_id  trip_id
1232        36           1     1232   77
         route_id  service_id  trip_id
1233        36           1     1233   78
         route_id  service_id  trip_id
1234        36           1     1234   79
         route_id  service_id  trip_id
1235        36           1     1235   80
         route_id  service_id  trip_id
1236        36           1     1236   81
         route_id  service_id  trip_id
1237        36           1     1237   82
         route_id  service_id  trip_id
1238        36           1     1238   83
         route_id  service_id  trip_id
1239        36           1     1239   84
         route_id  service_id  trip_id
1240        36           1     1240   85
         route_id  service_id  trip_id
1241        36           1     1241   86
         route_id  service_id  trip_id
1242        36           1     1242   87
         route_id  service_id  trip_id
1243        36           1     1243   88
         route_id  service_id  trip_id
1244        36           1     1244   89
         route_id  service_id  trip_id
1245        36           1     1245   90
         route_id  service_id  trip_id
1246        36           1     1246   91
         route_id  service_id  trip_id
1247        36           1     1247   92
         route_id  service_id  trip_id
1248        36           1     1248   93
         route_id  service_id  trip_id
1249        36           1     1249   94
         route_id  service_id  trip_id
1250        36           1     1250   95
         route_id  service_id  trip_id
1251        36           1     1251   96
         route_id  service_id  trip_id
1252        36           1     1252   97
         route_id  service_id  trip_id
1253        36           1     1253   98
         route_id  service_id  trip_id
1254        36           1     1254   99
         route_id  service_id  trip_id
1255        36           1     1255   100
         route_id  service_id  trip_id
1256        36           1     1256   101
         route_id  service_id  trip_id
1257        36           1     1257   102
         route_id  service_id  trip_id
1258        36           1     1258   103
         route_id  service_id  trip_id
1259        36           1     1259   104
         route_id  service_id  trip_id
1260        36           1     1260   105
         route_id  service_id  trip_id
1261        36           1     1261   106
         route_id  service_id  trip_id
1262        36           1     1262   107
         route_id  service_id  trip_id
1263        36           1     1263   108
         route_id  service_id  trip_id
1264        36           1     1264   109
         route_id  service_id  trip_id
1265        36           1     1265   110
         route_id  service_id  trip_id
1266        36           1     1266   111
         route_id  service_id  trip_id
1267        36           1     1267   112
         route_id  service_id  trip_id
1268        36           1     1268   113
         route_id  service_id  trip_id
1269        36           1     1269   114
         route_id  service_id  trip_id
1270        36           1     1270   115
         route_id  service_id  trip_id
1271        36           1     1271   116
         route_id  service_id  trip_id
1272        36           1     1272   117
         route_id  service_id  trip_id
1273        36           1     1273   118
         route_id  service_id  trip_id
1274        36           1     1274   119
         route_id  service_id  trip_id
1275        36           1     1275   120
         route_id  service_id  trip_id
1276        36           1     1276   121
         route_id  service_id  trip_id
1277        36           1     1277   122
         route_id  service_id  trip_id
1278        36           1     1278   123
         route_id  service_id  trip_id
1279        36           1     1279   124
         route_id  service_id  trip_id
1280        36           1     1280   125
         route_id  service_id  trip_id
1281        36           1     1281   126
         route_id  service_id  trip_id
1282        36           1     1282   127
         route_id  service_id  trip_id
1283        36           1     1283   128
         route_id  service_id  trip_id
1284        36           1     1284   129
         route_id  service_id  trip_id
1285        36           1     1285   130
         route_id  service_id  trip_id
1286        36           1     1286   131
         route_id  service_id  trip_id
1287        36           1     1287   132
         route_id  service_id  trip_id
1288        36           1     1288   133
         route_id  service_id  trip_id
1289        36           1     1289   134
         route_id  service_id  trip_id
1290        36           1     1290   135
         route_id  service_id  trip_id
1291        36           1     1291   136
         route_id  service_id  trip_id
1292        36           1     1292   137
         route_id  service_id  trip_id
1293        36           1     1293   138
         route_id  service_id  trip_id
1294        36           1     1294   139
         route_id  service_id  trip_id
1295        36           1     1295   140
         route_id  service_id  trip_id
1296        36           1     1296   141
         route_id  service_id  trip_id
1297        36           1     1297   142
         route_id  service_id  trip_id
1896        69           1     1896   143
         route_id  service_id  trip_id
1897        69           1     1897   144
         route_id  service_id  trip_id
1898        69           1     1898   145
         route_id  service_id  trip_id
1899        69           1     1899   146
         route_id  service_id  trip_id
1900        69           1     1900   147
         route_id  service_id  trip_id
1901        69           1     1901   148
         route_id  service_id  trip_id
1902        69           1     1902   149
         route_id  service_id  trip_id
1903        69           1     1903   150
         route_id  service_id  trip_id
1904        69           1     1904   151
         route_id  service_id  trip_id
1905        69           1     1905   152
         route_id  service_id  trip_id
1906        69           1     1906   153
         route_id  service_id  trip_id
1907        69           1     1907   154
         route_id  service_id  trip_id
1908        69           1     1908   155
         route_id  service_id  trip_id
1909        69           1     1909   156
         route_id  service_id  trip_id
1910        69           1     1910   157
         route_id  service_id  trip_id
1911        69           1     1911   158
         route_id  service_id  trip_id
1912        69           1     1912   159
         route_id  service_id  trip_id
1913        69           1     1913   160
         route_id  service_id  trip_id
1914        69           1     1914   161
         route_id  service_id  trip_id
1915        69           1     1915   162
         route_id  service_id  trip_id
1916        69           1     1916   163
         route_id  service_id  trip_id
1917        69           1     1917   164
         route_id  service_id  trip_id
1918        69           1     1918   165
         route_id  service_id  trip_id
1919        69           1     1919   166

         route_id  service_id  trip_id
3375        36           1     3375   167
         route_id  service_id  trip_id
3376        36           1     3376   168
         route_id  service_id  trip_id
3377        36           1     3377   169
         route_id  service_id  trip_id
3378        36           1     3378   170
         route_id  service_id  trip_id
3379        36           1     3379   171
         route_id  service_id  trip_id
3380        36           1     3380   172
         route_id  service_id  trip_id
3381        36           1     3381   173
         route_id  service_id  trip_id
3382        36           1     3382   174
         route_id  service_id  trip_id
3383        36           1     3383   175
         route_id  service_id  trip_id
3750       168           1     3750   176
         route_id  service_id  trip_id
3751       168           1     3751   177
         route_id  service_id  trip_id
3752       168           1     3752   178
         route_id  service_id  trip_id
3753       168           1     3753   179
         route_id  service_id  trip_id
3754       168           1     3754   180
         route_id  service_id  trip_id
3755       168           1     3755   181
         route_id  service_id  trip_id
3756       168           1     3756   182
         route_id  service_id  trip_id
3757       168           1     3757   183
         route_id  service_id  trip_id
3758       168           1     3758   184
         route_id  service_id  trip_id
3759       168           1     3759   185
         route_id  service_id  trip_id
3760       168           1     3760   186
         route_id  service_id  trip_id
3761       168           1     3761   187
         route_id  service_id  trip_id
3762       168           1     3762   188
         route_id  service_id  trip_id
3763       168           1     3763   189
         route_id  service_id  trip_id
3764       168           1     3764   190
         route_id  service_id  trip_id
3765       168           1     3765   191
         route_id  service_id  trip_id
3766       168           1     3766   192
         route_id  service_id  trip_id
3767       168           1     3767   193
         route_id  service_id  trip_id
3768       168           1     3768   194
         route_id  service_id  trip_id
3769       168           1     3769   195
         route_id  service_id  trip_id
3770       168           1     3770   196
         route_id  service_id  trip_id
3771       168           1     3771   197
         route_id  service_id  trip_id
3772       168           1     3772   198
         route_id  service_id  trip_id
3773       168           1     3773   199
         route_id  service_id  trip_id
3774       168           1     3774   200
         route_id  service_id  trip_id
3775       168           1     3775   201
         route_id  service_id  trip_id
3776       168           1     3776   202
         route_id  service_id  trip_id
3777       168           1     3777   203
         route_id  service_id  trip_id
3778       168           1     3778   204
         route_id  service_id  trip_id
3779       168           1     3779   205
         route_id  service_id  trip_id
3780       168           1     3780   206
         route_id  service_id  trip_id
3781       168           1     3781   207
         route_id  service_id  trip_id
3782       168           1     3782   208
         route_id  service_id  trip_id
3783       168           1     3783   209
         route_id  service_id  trip_id
3784       168           1     3784   210
         route_id  service_id  trip_id
3785       168           1     3785   211
         route_id  service_id  trip_id
3786       168           1     3786   212
         route_id  service_id  trip_id
3787       168           1     3787   213
         route_id  service_id  trip_id
3788       168           1     3788   214
         route_id  service_id  trip_id
3789       168           1     3789   215
         route_id  service_id  trip_id
3790       168           1     3790   216
         route_id  service_id  trip_id
3791       168           1     3791   217
         route_id  service_id  trip_id
3792       168           1     3792   218
         route_id  service_id  trip_id
3793       168           1     3793   219
         route_id  service_id  trip_id
4200       179           1     4200   220
         route_id  service_id  trip_id
4201       179           1     4201   221
         route_id  service_id  trip_id
4202       179           1     4202   222
         route_id  service_id  trip_id
4203       179           1     4203   223
         route_id  service_id  trip_id
4204       179           1     4204   224
         route_id  service_id  trip_id
4205       179           1     4205   225
         route_id  service_id  trip_id
4206       179           1     4206   226
         route_id  service_id  trip_id
4207       179           1     4207   227
         route_id  service_id  trip_id
4208       179           1     4208   228
         route_id  service_id  trip_id
4209       179           1     4209   229
         route_id  service_id  trip_id
4210       179           1     4210   230
         route_id  service_id  trip_id
4211       179           1     4211   231
         route_id  service_id  trip_id
4212       179           1     4212   232
         route_id  service_id  trip_id
4213       179           1     4213   233
         route_id  service_id  trip_id
4214       179           1     4214   234
         route_id  service_id  trip_id
4215       179           1     4215   235
         route_id  service_id  trip_id
4216       179           1     4216   236
         route_id  service_id  trip_id
4217       179           1     4217   237
         route_id  service_id  trip_id
4218       179           1     4218   238
         route_id  service_id  trip_id
4219       179           1     4219   239
         route_id  service_id  trip_id
4220       179           1     4220   240
         route_id  service_id  trip_id
4221       179           1     4221   241
         route_id  service_id  trip_id
4222       179           1     4222   242
         route_id  service_id  trip_id
4223       179           1     4223   243
         route_id  service_id  trip_id
4224       179           1     4224   244
         route_id  service_id  trip_id
4225       179           1     4225   245
         route_id  service_id  trip_id
4226       179           1     4226   246
         route_id  service_id  trip_id
4227       179           1     4227   247
         route_id  service_id  trip_id
4228       179           1     4228   248
         route_id  service_id  trip_id
4229       179           1     4229   249
         route_id  service_id  trip_id
4230       179           1     4230   250
         route_id  service_id  trip_id
4231       179           1     4231   251
         route_id  service_id  trip_id
4232       179           1     4232   252
         route_id  service_id  trip_id
4233       179           1     4233   253
         route_id  service_id  trip_id
4234       179           1     4234   254
         route_id  service_id  trip_id
4235       179           1     4235   255
         route_id  service_id  trip_id
4236       179           1     4236   256
         route_id  service_id  trip_id
4237       179           1     4237   257
         route_id  service_id  trip_id
4238       179           1     4238   258
         route_id  service_id  trip_id
4239       179           1     4239   259
         route_id  service_id  trip_id
4240       179           1     4240   260
         route_id  service_id  trip_id
4241       179           1     4241   261
         route_id  service_id  trip_id
4242       179           1     4242   262
         route_id  service_id  trip_id
4243       179           1     4243   263
         route_id  service_id  trip_id
4244       179           1     4244   264
         route_id  service_id  trip_id
4245       179           1     4245   265
         route_id  service_id  trip_id
4246       179           1     4246   266
         route_id  service_id  trip_id
4247       179           1     4247   267
         route_id  service_id  trip_id
4248       179           1     4248   268
         route_id  service_id  trip_id
4249       179           1     4249   269
         route_id  service_id  trip_id
4250       179           1     4250   270
         route_id  service_id  trip_id
4251       179           1     4251   271
         route_id  service_id  trip_id
4252       179           1     4252   272
         route_id  service_id  trip_id
4253       179           1     4253   273
         route_id  service_id  trip_id
4254       179           1     4254   274
         route_id  service_id  trip_id
4255       179           1     4255   275
         route_id  service_id  trip_id
4256       179           1     4256   276
         route_id  service_id  trip_id
4257       179           1     4257   277
         route_id  service_id  trip_id
4258       179           1     4258   278
         route_id  service_id  trip_id
4259       179           1     4259   279
         route_id  service_id  trip_id
4260       179           1     4260   280
         route_id  service_id  trip_id
4261       179           1     4261   281
         route_id  service_id  trip_id
4262       179           1     4262   282
         route_id  service_id  trip_id
4263       179           1     4263   283
         route_id  service_id  trip_id
4264       179           1     4264   284
         route_id  service_id  trip_id
4265       179           1     4265   285
         route_id  service_id  trip_id
4266       179           1     4266   286
         route_id  service_id  trip_id
4267       179           1     4267   287
         route_id  service_id  trip_id
4268       179           1     4268   288
         route_id  service_id  trip_id
4269       179           1     4269   289
         route_id  service_id  trip_id
4270       179           1     4270   290
         route_id  service_id  trip_id
4271       179           1     4271   291
         route_id  service_id  trip_id
4272       179           1     4272   292
         route_id  service_id  trip_id
4273       179           1     4273   293
         route_id  service_id  trip_id
4274       179           1     4274   294
         route_id  service_id  trip_id
4275       179           1     4275   295
         route_id  service_id  trip_id
4276       179           1     4276   296
         route_id  service_id  trip_id
4277       179           1     4277   297
         route_id  service_id  trip_id
4278       179           1     4278   298
         route_id  service_id  trip_id
4279       179           1     4279   299
         route_id  service_id  trip_id
4280       179           1     4280   300
         route_id  service_id  trip_id
4281       179           1     4281   301
         route_id  service_id  trip_id
4282       179           1     4282   302
         route_id  service_id  trip_id
4283       179           1     4283   303
         route_id  service_id  trip_id
4284       179           1     4284   304
         route_id  service_id  trip_id
4285       179           1     4285   305
         route_id  service_id  trip_id
4286       179           1     4286   306
         route_id  service_id  trip_id
4287       179           1     4287   307
         route_id  service_id  trip_id
4288       179           1     4288   308
         route_id  service_id  trip_id
4289       179           1     4289   309
         route_id  service_id  trip_id
4290       179           1     4290   310
         route_id  service_id  trip_id
4291       179           1     4291   311
         route_id  service_id  trip_id
4292       179           1     4292   312
         route_id  service_id  trip_id
4293       179           1     4293   313
         route_id  service_id  trip_id
4294       179           1     4294   314
         route_id  service_id  trip_id
4295       179           1     4295   315
         route_id  service_id  trip_id
4296       179           1     4296   316
         route_id  service_id  trip_id
4297       179           1     4297   317
         route_id  service_id  trip_id
4298       179           1     4298   318
         route_id  service_id  trip_id
4299       179           1     4299   319
         route_id  service_id  trip_id
4300       179           1     4300   320
         route_id  service_id  trip_id
4301       179           1     4301   321
         route_id  service_id  trip_id
4302       179           1     4302   322
         route_id  service_id  trip_id
4303       179           1     4303   323
         route_id  service_id  trip_id
4304       179           1     4304   324
         route_id  service_id  trip_id
4305       179           1     4305   325
         route_id  service_id  trip_id
4306       179           1     4306   326
         route_id  service_id  trip_id
4307       179           1     4307   327
         route_id  service_id  trip_id
4308       179           1     4308   328
         route_id  service_id  trip_id
4309       179           1     4309   329
         route_id  service_id  trip_id
4310       179           1     4310   330
         route_id  service_id  trip_id
4311       179           1     4311   331
         route_id  service_id  trip_id
4312       179           1     4312   332
         route_id  service_id  trip_id
4313       179           1     4313   333
         route_id  service_id  trip_id
4314       179           1     4314   334
         route_id  service_id  trip_id
4315       179           1     4315   335
         route_id  service_id  trip_id
4316       179           1     4316   336
         route_id  service_id  trip_id
4317       179           1     4317   337
         route_id  service_id  trip_id
4318       179           1     4318   338
         route_id  service_id  trip_id
4319       179           1     4319   339
         route_id  service_id  trip_id
4320       179           1     4320   340
         route_id  service_id  trip_id
4321       179           1     4321   341
         route_id  service_id  trip_id
4322       179           1     4322   342
         route_id  service_id  trip_id
4323       179           1     4323   343
         route_id  service_id  trip_id
4324       179           1     4324   344
         route_id  service_id  trip_id
4325       179           1     4325   345
         route_id  service_id  trip_id
4326       179           1     4326   346
         route_id  service_id  trip_id
4327       179           1     4327   347
         route_id  service_id  trip_id
5258       200           1     5258   348
         route_id  service_id  trip_id
5259       200           1     5259   349
         route_id  service_id  trip_id
5260       200           1     5260   350
         route_id  service_id  trip_id
5261       200           1     5261   351
         route_id  service_id  trip_id
5262       200           1     5262   352
         route_id  service_id  trip_id
5263       200           1     5263   353

         route_id  service_id  trip_id
5264       200           1     5264   354
         route_id  service_id  trip_id
5265       200           1     5265   355
         route_id  service_id  trip_id
5266       200           1     5266   356
         route_id  service_id  trip_id
5267       200           1     5267   357
         route_id  service_id  trip_id
5268       200           1     5268   358
         route_id  service_id  trip_id
5269       200           1     5269   359
         route_id  service_id  trip_id
5270       200           1     5270   360
         route_id  service_id  trip_id
5271       200           1     5271   361
         route_id  service_id  trip_id
5272       200           1     5272   362
         route_id  service_id  trip_id
5273       200           1     5273   363
         route_id  service_id  trip_id
5274       200           1     5274   364
         route_id  service_id  trip_id
5275       200           1     5275   365
         route_id  service_id  trip_id
5276       200           1     5276   366
         route_id  service_id  trip_id
5277       200           1     5277   367
         route_id  service_id  trip_id
5278       200           1     5278   368
         route_id  service_id  trip_id
5279       200           1     5279   369
         route_id  service_id  trip_id
5280       200           1     5280   370
         route_id  service_id  trip_id
5281       200           1     5281   371
         route_id  service_id  trip_id
5282       200           1     5282   372
         route_id  service_id  trip_id
5283       200           1     5283   373
         route_id  service_id  trip_id
5284       200           1     5284   374
         route_id  service_id  trip_id
5285       200           1     5285   375
         route_id  service_id  trip_id
5286       200           1     5286   376
         route_id  service_id  trip_id
5287       200           1     5287   377
         route_id  service_id  trip_id
5288       200           1     5288   378
         route_id  service_id  trip_id
5289       200           1     5289   379
         route_id  service_id  trip_id
5290       200           1     5290   380
         route_id  service_id  trip_id
5291       200           1     5291   381
         route_id  service_id  trip_id
5292       200           1     5292   382
         route_id  service_id  trip_id
5293       200           1     5293   383
         route_id  service_id  trip_id
5294       200           1     5294   384
         route_id  service_id  trip_id
5295       200           1     5295   385
         route_id  service_id  trip_id
5296       200           1     5296   386
         route_id  service_id  trip_id
5297       200           1     5297   387
         route_id  service_id  trip_id
5298       200           1     5298   388
         route_id  service_id  trip_id
5299       200           1     5299   389
         route_id  service_id  trip_id
5300       200           1     5300   390
         route_id  service_id  trip_id
5301       200           1     5301   391
         route_id  service_id  trip_id
5302       200           1     5302   392
         route_id  service_id  trip_id
5303       200           1     5303   393
         route_id  service_id  trip_id
5304       200           1     5304   394
         route_id  service_id  trip_id
5305       200           1     5305   395
         route_id  service_id  trip_id
5306       200           1     5306   396
         route_id  service_id  trip_id
5307       200           1     5307   397
         route_id  service_id  trip_id
5308       200           1     5308   398
         route_id  service_id  trip_id
5309       200           1     5309   399
         route_id  service_id  trip_id
5310       200           1     5310   400
         route_id  service_id  trip_id
5311       200           1     5311   401
         route_id  service_id  trip_id
5312       200           1     5312   402
         route_id  service_id  trip_id
5313       200           1     5313   403
         route_id  service_id  trip_id
5314       200           1     5314   404
         route_id  service_id  trip_id
5315       200           1     5315   405
         route_id  service_id  trip_id
5316       200           1     5316   406
         route_id  service_id  trip_id
5317       200           1     5317   407
         route_id  service_id  trip_id
5318       200           1     5318   408
         route_id  service_id  trip_id
5319       200           1     5319   409
         route_id  service_id  trip_id
5320       200           1     5320   410
         route_id  service_id  trip_id
5321       200           1     5321   411
         route_id  service_id  trip_id
5322       200           1     5322   412
         route_id  service_id  trip_id
5323       200           1     5323   413
         route_id  service_id  trip_id
5324       200           1     5324   414
         route_id  service_id  trip_id
5325       200           1     5325   415
         route_id  service_id  trip_id
5326       200           1     5326   416
         route_id  service_id  trip_id
5327       200           1     5327   417
         route_id  service_id  trip_id
5328       200           1     5328   418
         route_id  service_id  trip_id
5329       200           1     5329   419
         route_id  service_id  trip_id
5330       200           1     5330   420
         route_id  service_id  trip_id
5331       200           1     5331   421
         route_id  service_id  trip_id
5332       200           1     5332   422
         route_id  service_id  trip_id
5333       200           1     5333   423
         route_id  service_id  trip_id
5334       200           1     5334   424
         route_id  service_id  trip_id
5335       200           1     5335   425
         route_id  service_id  trip_id
5336       200           1     5336   426
          route_id  service_id  trip_id
12821       168           1    12821   427
          route_id  service_id  trip_id
12822       168           1    12822   428
          route_id  service_id  trip_id
12823       168           1    12823   429
          route_id  service_id  trip_id
12824       168           1    12824   430
          route_id  service_id  trip_id
12825       168           1    12825   431
          route_id  service_id  trip_id
12826       168           1    12826   432
          route_id  service_id  trip_id
12827       168           1    12827   433
          route_id  service_id  trip_id
12828       168           1    12828   434
          route_id  service_id  trip_id
12829       168           1    12829   435
          route_id  service_id  trip_id
12830       168           1    12830   436
          route_id  service_id  trip_id
12831       168           1    12831   437
          route_id  service_id  trip_id
12832       168           1    12832   438
          route_id  service_id  trip_id
12833       168           1    12833   439
          route_id  service_id  trip_id
12834       168           1    12834   440
          route_id  service_id  trip_id
12835       168           1    12835   441
          route_id  service_id  trip_id
12836       168           1    12836   442
          route_id  service_id  trip_id
12837       168           1    12837   443
          route_id  service_id  trip_id
12838       168           1    12838   444
          route_id  service_id  trip_id
12839       168           1    12839   445
          route_id  service_id  trip_id
12840       168           1    12840   446
          route_id  service_id  trip_id
12841       168           1    12841   447
          route_id  service_id  trip_id
12842       168           1    12842   448
          route_id  service_id  trip_id
12843       168           1    12843   449
          route_id  service_id  trip_id
12844       168           1    12844   450
          route_id  service_id  trip_id
12845       168           1    12845   451
          route_id  service_id  trip_id
12846       168           1    12846   452
          route_id  service_id  trip_id
12847       168           1    12847   453
          route_id  service_id  trip_id
12848       168           1    12848   454
          route_id  service_id  trip_id
12849       168           1    12849   455
          route_id  service_id  trip_id
12850       168           1    12850   456
          route_id  service_id  trip_id
12851       168           1    12851   457
          route_id  service_id  trip_id
12852       168           1    12852   458
          route_id  service_id  trip_id
12853       168           1    12853   459
          route_id  service_id  trip_id
12854       168           1    12854   460
          route_id  service_id  trip_id
12855       168           1    12855   461
          route_id  service_id  trip_id
12856       168           1    12856   462
          route_id  service_id  trip_id
12857       168           1    12857   463
          route_id  service_id  trip_id
12858       168           1    12858   464
          route_id  service_id  trip_id
12859       168           1    12859   465
          route_id  service_id  trip_id
12860       168           1    12860   466
          route_id  service_id  trip_id
12861       168           1    12861   467
          route_id  service_id  trip_id
12862       168           1    12862   468
          route_id  service_id  trip_id
12863       168           1    12863   469
          route_id  service_id  trip_id
12864       168           1    12864   470
          route_id  service_id  trip_id
12865       168           1    12865   471
          route_id  service_id  trip_id
12866       168           1    12866   472
          route_id  service_id  trip_id
12867       168           1    12867   473
          route_id  service_id  trip_id
12868       168           1    12868   474
          route_id  service_id  trip_id
12869       168           1    12869   475
          route_id  service_id  trip_id
12870       168           1    12870   476
          route_id  service_id  trip_id
12871       168           1    12871   477
          route_id  service_id  trip_id
12872       168           1    12872   478
          route_id  service_id  trip_id
12873       168           1    12873   479
          route_id  service_id  trip_id
12874       168           1    12874   480
          route_id  service_id  trip_id
12875       168           1    12875   481
          route_id  service_id  trip_id
12876       168           1    12876   482
          route_id  service_id  trip_id
12877       168           1    12877   483
          route_id  service_id  trip_id
12878       168           1    12878   484
          route_id  service_id  trip_id
12879       168           1    12879   485
          route_id  service_id  trip_id
12880       168           1    12880   486
          route_id  service_id  trip_id
12881       168           1    12881   487
          route_id  service_id  trip_id
12882       168           1    12882   488
          route_id  service_id  trip_id
12883       168           1    12883   489
          route_id  service_id  trip_id
12884       168           1    12884   490
          route_id  service_id  trip_id
12885       168           1    12885   491
          route_id  service_id  trip_id
12886       168           1    12886   492
          route_id  service_id  trip_id
12887       168           1    12887   493
          route_id  service_id  trip_id
12888       168           1    12888   494
          route_id  service_id  trip_id
12889       168           1    12889   495
          route_id  service_id  trip_id
12890       168           1    12890   496
          route_id  service_id  trip_id
12891       168           1    12891   497
          route_id  service_id  trip_id
12892       168           1    12892   498
          route_id  service_id  trip_id
12976       448           1    12976   499
          route_id  service_id  trip_id
12977       448           1    12977   500
          route_id  service_id  trip_id
12978       448           1    12978   501
          route_id  service_id  trip_id
12979       448           1    12979   502
          route_id  service_id  trip_id
12980       448           1    12980   503
          route_id  service_id  trip_id
12981       448           1    12981   504
          route_id  service_id  trip_id
12982       448           1    12982   505
          route_id  service_id  trip_id
12983       448           1    12983   506
          route_id  service_id  trip_id
12984       448           1    12984   507
          route_id  service_id  trip_id
12985       448           1    12985   508
          route_id  service_id  trip_id
12986       448           1    12986   509
          route_id  service_id  trip_id
12987       448           1    12987   510
          route_id  service_id  trip_id
12988       448           1    12988   511
          route_id  service_id  trip_id
12989       448           1    12989   512
          route_id  service_id  trip_id
12990       448           1    12990   513
          route_id  service_id  trip_id
12991       448           1    12991   514
          route_id  service_id  trip_id
12992       448           1    12992   515
          route_id  service_id  trip_id
12993       448           1    12993   516
          route_id  service_id  trip_id
12994       448           1    12994   517
          route_id  service_id  trip_id
12995       448           1    12995   518
          route_id  service_id  trip_id
12996       448           1    12996   519
          route_id  service_id  trip_id
12997       448           1    12997   520
          route_id  service_id  trip_id
12998       448           1    12998   521
          route_id  service_id  trip_id
12999       448           1    12999   522
          route_id  service_id  trip_id
13000       448           1    13000   523
          route_id  service_id  trip_id
13001       448           1    13001   524
          route_id  service_id  trip_id
13002       448           1    13002   525
          route_id  service_id  trip_id
13003       448           1    13003   526
          route_id  service_id  trip_id
13004       448           1    13004   527
          route_id  service_id  trip_id
13005       448           1    13005   528
          route_id  service_id  trip_id
13006       448           1    13006   529
          route_id  service_id  trip_id
13007       448           1    13007   530
          route_id  service_id  trip_id
13008       448           1    13008   531
          route_id  service_id  trip_id
13009       448           1    13009   532
          route_id  service_id  trip_id
13010       448           1    13010   533
          route_id  service_id  trip_id
13011       448           1    13011   534
          route_id  service_id  trip_id
13012       448           1    13012   535
          route_id  service_id  trip_id
13013       448           1    13013   536
          route_id  service_id  trip_id
13014       448           1    13014   537
          route_id  service_id  trip_id
13015       448           1    13015   538
          route_id  service_id  trip_id
13016       448           1    13016   539
          route_id  service_id  trip_id
13017       448           1    13017   540
          route_id  service_id  trip_id
13018       448           1    13018   541
          route_id  service_id  trip_id

13019       448           1    13019   542
          route_id  service_id  trip_id
13020       448           1    13020   543
          route_id  service_id  trip_id
13021       448           1    13021   544
          route_id  service_id  trip_id
13022       448           1    13022   545
          route_id  service_id  trip_id
13023       448           1    13023   546
          route_id  service_id  trip_id
13024       448           1    13024   547
          route_id  service_id  trip_id
13025       448           1    13025   548
          route_id  service_id  trip_id
13026       448           1    13026   549
          route_id  service_id  trip_id
13027       448           1    13027   550
          route_id  service_id  trip_id
13028       448           1    13028   551
          route_id  service_id  trip_id
13029       448           1    13029   552
          route_id  service_id  trip_id
13030       448           1    13030   553
          route_id  service_id  trip_id
13031       448           1    13031   554
          route_id  service_id  trip_id
13032       448           1    13032   555
          route_id  service_id  trip_id
13033       448           1    13033   556
          route_id  service_id  trip_id
13034       448           1    13034   557
          route_id  service_id  trip_id
13035       448           1    13035   558
          route_id  service_id  trip_id
13036       448           1    13036   559
          route_id  service_id  trip_id
13037       448           1    13037   560
          route_id  service_id  trip_id
13038       448           1    13038   561
          route_id  service_id  trip_id
13039       448           1    13039   562
          route_id  service_id  trip_id
13040       448           1    13040   563
          route_id  service_id  trip_id
13041       448           1    13041   564
          route_id  service_id  trip_id
13042       448           1    13042   565
          route_id  service_id  trip_id
13043       448           1    13043   566
          route_id  service_id  trip_id
13044       448           1    13044   567
          route_id  service_id  trip_id
13045       448           1    13045   568
          route_id  service_id  trip_id
13046       448           1    13046   569
          route_id  service_id  trip_id
13047       448           1    13047   570
          route_id  service_id  trip_id
13048       448           1    13048   571
          route_id  service_id  trip_id
13049       448           1    13049   572
          route_id  service_id  trip_id
13050       448           1    13050   573
          route_id  service_id  trip_id
13051       448           1    13051   574
          route_id  service_id  trip_id
13052       448           1    13052   575
          route_id  service_id  trip_id
13053       448           1    13053   576
          route_id  service_id  trip_id
13054       448           1    13054   577
          route_id  service_id  trip_id
13055       448           1    13055   578
          route_id  service_id  trip_id
13056       448           1    13056   579
          route_id  service_id  trip_id
13057       448           1    13057   580
          route_id  service_id  trip_id
13058       448           1    13058   581
          route_id  service_id  trip_id
13099       450           1    13099   582
          route_id  service_id  trip_id
13100       450           1    13100   583
          route_id  service_id  trip_id
13101       450           1    13101   584
          route_id  service_id  trip_id
13102       450           1    13102   585
          route_id  service_id  trip_id
13103       450           1    13103   586
          route_id  service_id  trip_id
13104       450           1    13104   587
          route_id  service_id  trip_id
13105       450           1    13105   588
          route_id  service_id  trip_id
13106       450           1    13106   589
          route_id  service_id  trip_id
13107       450           1    13107   590
          route_id  service_id  trip_id
13108       450           1    13108   591
          route_id  service_id  trip_id
13109       450           1    13109   592
          route_id  service_id  trip_id
13110       450           1    13110   593
          route_id  service_id  trip_id
13111       450           1    13111   594
          route_id  service_id  trip_id
13112       450           1    13112   595
          route_id  service_id  trip_id
13113       450           1    13113   596
          route_id  service_id  trip_id
13114       450           1    13114   597
          route_id  service_id  trip_id
13115       450           1    13115   598
          route_id  service_id  trip_id
13116       450           1    13116   599
          route_id  service_id  trip_id
13117       450           1    13117   600
          route_id  service_id  trip_id
13118       450           1    13118   601
          route_id  service_id  trip_id
13119       450           1    13119   602
          route_id  service_id  trip_id
13120       450           1    13120   603
          route_id  service_id  trip_id
13121       450           1    13121   604
          route_id  service_id  trip_id
13122       450           1    13122   605
          route_id  service_id  trip_id
13123       450           1    13123   606
          route_id  service_id  trip_id
13124       450           1    13124   607
          route_id  service_id  trip_id
13125       450           1    13125   608
          route_id  service_id  trip_id
13126       450           1    13126   609
          route_id  service_id  trip_id
13127       450           1    13127   610
          route_id  service_id  trip_id
13128       450           1    13128   611
          route_id  service_id  trip_id
13129       450           1    13129   612
          route_id  service_id  trip_id
13130       450           1    13130   613
          route_id  service_id  trip_id
13131       450           1    13131   614
          route_id  service_id  trip_id
13132       450           1    13132   615
          route_id  service_id  trip_id
13133       450           1    13133   616
          route_id  service_id  trip_id
13134       450           1    13134   617
          route_id  service_id  trip_id
13135       450           1    13135   618
          route_id  service_id  trip_id
13136       450           1    13136   619
          route_id  service_id  trip_id
13137       450           1    13137   620
          route_id  service_id  trip_id
13138       450           1    13138   621
          route_id  service_id  trip_id
13241       458           1    13241   622
          route_id  service_id  trip_id
13242       458           1    13242   623
          route_id  service_id  trip_id
13243       458           1    13243   624
          route_id  service_id  trip_id
13244       458           1    13244   625
          route_id  service_id  trip_id
13245       458           1    13245   626
          route_id  service_id  trip_id
13246       458           1    13246   627
          route_id  service_id  trip_id
13247       458           1    13247   628
          route_id  service_id  trip_id
13248       458           1    13248   629
          route_id  service_id  trip_id
13249       458           1    13249   630
          route_id  service_id  trip_id
13250       458           1    13250   631
          route_id  service_id  trip_id
13251       458           1    13251   632
          route_id  service_id  trip_id
13252       458           1    13252   633
          route_id  service_id  trip_id
13253       458           1    13253   634
          route_id  service_id  trip_id
13254       458           1    13254   635
          route_id  service_id  trip_id
13255       458           1    13255   636
          route_id  service_id  trip_id
13256       458           1    13256   637
          route_id  service_id  trip_id
13257       458           1    13257   638
          route_id  service_id  trip_id
13258       458           1    13258   639
          route_id  service_id  trip_id
13259       458           1    13259   640
          route_id  service_id  trip_id
13260       458           1    13260   641
          route_id  service_id  trip_id
13261       458           1    13261   642
          route_id  service_id  trip_id
13262       458           1    13262   643
          route_id  service_id  trip_id
13263       458           1    13263   644
          route_id  service_id  trip_id
13264       458           1    13264   645
          route_id  service_id  trip_id
13265       458           1    13265   646
          route_id  service_id  trip_id
13266       458           1    13266   647
          route_id  service_id  trip_id
13267       458           1    13267   648
          route_id  service_id  trip_id
13268       458           1    13268   649
          route_id  service_id  trip_id
14129       476           1    14129   650
          route_id  service_id  trip_id
14130       476           1    14130   651
          route_id  service_id  trip_id
14131       476           1    14131   652
          route_id  service_id  trip_id
14132       476           1    14132   653
          route_id  service_id  trip_id
14133       476           1    14133   654
          route_id  service_id  trip_id
14134       476           1    14134   655
          route_id  service_id  trip_id
14135       476           1    14135   656
          route_id  service_id  trip_id
14136       476           1    14136   657
          route_id  service_id  trip_id
14137       476           1    14137   658
          route_id  service_id  trip_id
14138       476           1    14138   659
          route_id  service_id  trip_id
14139       476           1    14139   660
          route_id  service_id  trip_id
14140       476           1    14140   661
          route_id  service_id  trip_id
14141       476           1    14141   662
          route_id  service_id  trip_id
14142       476           1    14142   663
          route_id  service_id  trip_id
14143       476           1    14143   664
          route_id  service_id  trip_id
14144       476           1    14144   665
          route_id  service_id  trip_id
14145       476           1    14145   666
          route_id  service_id  trip_id
14146       476           1    14146   667
          route_id  service_id  trip_id
14147       476           1    14147   668
          route_id  service_id  trip_id
14148       476           1    14148   669
          route_id  service_id  trip_id
14149       476           1    14149   670
          route_id  service_id  trip_id
14150       476           1    14150   671
          route_id  service_id  trip_id
14151       476           1    14151   672
          route_id  service_id  trip_id
14152       476           1    14152   673
          route_id  service_id  trip_id
14153       476           1    14153   674
          route_id  service_id  trip_id
14154       476           1    14154   675
          route_id  service_id  trip_id
14155       476           1    14155   676
          route_id  service_id  trip_id
14156       476           1    14156   677
          route_id  service_id  trip_id
14157       476           1    14157   678
          route_id  service_id  trip_id
14158       476           1    14158   679
          route_id  service_id  trip_id
14159       476           1    14159   680
          route_id  service_id  trip_id
14160       476           1    14160   681
          route_id  service_id  trip_id
14161       476           1    14161   682
          route_id  service_id  trip_id
14162       476           1    14162   683
          route_id  service_id  trip_id
14163       476           1    14163   684
          route_id  service_id  trip_id
14164       476           1    14164   685
          route_id  service_id  trip_id
14165       476           1    14165   686
          route_id  service_id  trip_id
14166       476           1    14166   687
          route_id  service_id  trip_id
14167       476           1    14167   688
          route_id  service_id  trip_id
14168       476           1    14168   689
          route_id  service_id  trip_id
14169       476           1    14169   690
          route_id  service_id  trip_id
14170       476           1    14170   691
          route_id  service_id  trip_id
14171       476           1    14171   692
          route_id  service_id  trip_id
14172       476           1    14172   693
          route_id  service_id  trip_id
14173       476           1    14173   694
          route_id  service_id  trip_id
14174       476           1    14174   695
          route_id  service_id  trip_id
14175       476           1    14175   696
          route_id  service_id  trip_id
14176       476           1    14176   697
          route_id  service_id  trip_id
14177       476           1    14177   698
          route_id  service_id  trip_id
14178       476           1    14178   699
          route_id  service_id  trip_id
14179       476           1    14179   700
          route_id  service_id  trip_id
14180       476           1    14180   701
          route_id  service_id  trip_id
14181       476           1    14181   702
          route_id  service_id  trip_id
14182       476           1    14182   703
          route_id  service_id  trip_id
14183       476           1    14183   704
          route_id  service_id  trip_id
14184       476           1    14184   705
          route_id  service_id  trip_id
14185       476           1    14185   706
          route_id  service_id  trip_id
14186       476           1    14186   707
          route_id  service_id  trip_id
14187       476           1    14187   708
          route_id  service_id  trip_id
14188       476           1    14188   709
          route_id  service_id  trip_id
14189       476           1    14189   710
          route_id  service_id  trip_id
14190       476           1    14190   711
          route_id  service_id  trip_id
14191       476           1    14191   712
          route_id  service_id  trip_id
14192       476           1    14192   713
          route_id  service_id  trip_id
14193       476           1    14193   714
          route_id  service_id  trip_id
14194       476           1    14194   715
          route_id  service_id  trip_id
14195       476           1    14195   716
          route_id  service_id  trip_id
14196       476           1    14196   717
          route_id  service_id  trip_id
14197       476           1    14197   718
          route_id  service_id  trip_id
14198       476           1    14198   719
          route_id  service_id  trip_id
14199       476           1    14199   720
          route_id  service_id  trip_id
14200       476           1    14200   721
          route_id  service_id  trip_id
14201       476           1    14201   722
          route_id  service_id  trip_id
14202       476           1    14202   723
          route_id  service_id  trip_id
14203       476           1    14203   724
          route_id  service_id  trip_id
14204       476           1    14204   725
          route_id  service_id  trip_id
14205       476           1    14205   726
          route_id  service_id  trip_id
14206       476           1    14206   727
          route_id  service_id  trip_id
14207       476           1    14207   728
          route_id  service_id  trip_id

14208       476           1    14208   729
          route_id  service_id  trip_id
14332       480           1    14332   730
          route_id  service_id  trip_id
14333       480           1    14333   731
          route_id  service_id  trip_id
14334       480           1    14334   732
          route_id  service_id  trip_id
14335       480           1    14335   733
          route_id  service_id  trip_id
14336       480           1    14336   734
          route_id  service_id  trip_id
14337       480           1    14337   735
          route_id  service_id  trip_id
14338       480           1    14338   736
          route_id  service_id  trip_id
14339       480           1    14339   737
          route_id  service_id  trip_id
14340       480           1    14340   738
          route_id  service_id  trip_id
14341       480           1    14341   739
          route_id  service_id  trip_id
14342       480           1    14342   740
          route_id  service_id  trip_id
14343       480           1    14343   741
          route_id  service_id  trip_id
14344       480           1    14344   742
          route_id  service_id  trip_id
14345       480           1    14345   743
          route_id  service_id  trip_id
14346       480           1    14346   744
          route_id  service_id  trip_id
14347       480           1    14347   745
          route_id  service_id  trip_id
14348       480           1    14348   746
          route_id  service_id  trip_id
14349       480           1    14349   747
          route_id  service_id  trip_id
14350       480           1    14350   748
          route_id  service_id  trip_id
14351       480           1    14351   749
          route_id  service_id  trip_id
14352       480           1    14352   750
          route_id  service_id  trip_id
14353       480           1    14353   751
          route_id  service_id  trip_id
14354       480           1    14354   752
          route_id  service_id  trip_id
14355       480           1    14355   753
          route_id  service_id  trip_id
14356       480           1    14356   754
          route_id  service_id  trip_id
14357       480           1    14357   755
          route_id  service_id  trip_id
14358       480           1    14358   756
          route_id  service_id  trip_id
14359       450           1    14359   757
          route_id  service_id  trip_id
14360       450           1    14360   758
          route_id  service_id  trip_id
14361       450           1    14361   759
          route_id  service_id  trip_id
14362       450           1    14362   760
          route_id  service_id  trip_id
14363       450           1    14363   761
          route_id  service_id  trip_id
14364       450           1    14364   762
          route_id  service_id  trip_id
14365       450           1    14365   763
          route_id  service_id  trip_id
14366       450           1    14366   764
          route_id  service_id  trip_id
14367       450           1    14367   765
          route_id  service_id  trip_id
14368       450           1    14368   766
          route_id  service_id  trip_id
14369       450           1    14369   767
          route_id  service_id  trip_id
14370       450           1    14370   768
          route_id  service_id  trip_id
14371       450           1    14371   769
          route_id  service_id  trip_id
14372       450           1    14372   770
          route_id  service_id  trip_id
14373       450           1    14373   771
          route_id  service_id  trip_id
14374       450           1    14374   772
          route_id  service_id  trip_id
14375       450           1    14375   773
          route_id  service_id  trip_id
14376       450           1    14376   774
          route_id  service_id  trip_id
14377       450           1    14377   775
          route_id  service_id  trip_id
14378       450           1    14378   776
          route_id  service_id  trip_id
14379       450           1    14379   777
          route_id  service_id  trip_id
14380       450           1    14380   778
          route_id  service_id  trip_id
14381       450           1    14381   779
          route_id  service_id  trip_id
14382       450           1    14382   780
          route_id  service_id  trip_id
14383       450           1    14383   781
          route_id  service_id  trip_id
14384       450           1    14384   782
          route_id  service_id  trip_id
14385       450           1    14385   783
          route_id  service_id  trip_id
14386       450           1    14386   784
          route_id  service_id  trip_id
14387       450           1    14387   785
          route_id  service_id  trip_id
14388       450           1    14388   786
          route_id  service_id  trip_id
14389       450           1    14389   787
          route_id  service_id  trip_id
14390       450           1    14390   788
          route_id  service_id  trip_id
14391       450           1    14391   789
          route_id  service_id  trip_id
14392       450           1    14392   790
          route_id  service_id  trip_id
14393       450           1    14393   791
          route_id  service_id  trip_id
14394       450           1    14394   792
          route_id  service_id  trip_id
14395       450           1    14395   793
          route_id  service_id  trip_id
14396       450           1    14396   794
          route_id  service_id  trip_id
14397       450           1    14397   795
          route_id  service_id  trip_id
14398       450           1    14398   796
          route_id  service_id  trip_id
14399       450           1    14399   797
          route_id  service_id  trip_id
14400       450           1    14400   798
          route_id  service_id  trip_id
14401       450           1    14401   799
          route_id  service_id  trip_id
14402       450           1    14402   800
          route_id  service_id  trip_id
14403       450           1    14403   801
          route_id  service_id  trip_id
14404       450           1    14404   802
          route_id  service_id  trip_id
14405       450           1    14405   803
          route_id  service_id  trip_id
14406       450           1    14406   804
          route_id  service_id  trip_id
14439       482           1    14439   805
          route_id  service_id  trip_id
14440       482           1    14440   806
          route_id  service_id  trip_id
14441       482           1    14441   807
          route_id  service_id  trip_id
14442       482           1    14442   808
          route_id  service_id  trip_id
14443       482           1    14443   809
          route_id  service_id  trip_id
14444       482           1    14444   810
          route_id  service_id  trip_id
14445       482           1    14445   811
          route_id  service_id  trip_id
14446       482           1    14446   812
          route_id  service_id  trip_id
14447       482           1    14447   813
          route_id  service_id  trip_id
14448       482           1    14448   814
          route_id  service_id  trip_id
14449       482           1    14449   815
          route_id  service_id  trip_id
14450       482           1    14450   816
          route_id  service_id  trip_id
14451       482           1    14451   817
          route_id  service_id  trip_id
14452       482           1    14452   818
          route_id  service_id  trip_id
14453       482           1    14453   819
          route_id  service_id  trip_id
14454       482           1    14454   820
          route_id  service_id  trip_id
14455       482           1    14455   821
          route_id  service_id  trip_id
14456       482           1    14456   822
          route_id  service_id  trip_id
14457       482           1    14457   823
          route_id  service_id  trip_id
14458       482           1    14458   824
          route_id  service_id  trip_id
14459       482           1    14459   825
          route_id  service_id  trip_id
14460       482           1    14460   826
          route_id  service_id  trip_id
14461       482           1    14461   827
          route_id  service_id  trip_id
14462       482           1    14462   828
          route_id  service_id  trip_id
14463       482           1    14463   829
          route_id  service_id  trip_id
14464       482           1    14464   830
          route_id  service_id  trip_id
14465       482           1    14465   831
          route_id  service_id  trip_id
14466       482           1    14466   832
          route_id  service_id  trip_id
14467       482           1    14467   833
          route_id  service_id  trip_id
14468       482           1    14468   834
          route_id  service_id  trip_id
14469       482           1    14469   835
          route_id  service_id  trip_id
14470       482           1    14470   836
          route_id  service_id  trip_id
15464       513           1    15464   837
          route_id  service_id  trip_id
15465       513           1    15465   838
          route_id  service_id  trip_id
15466       513           1    15466   839
          route_id  service_id  trip_id
15467       513           1    15467   840
          route_id  service_id  trip_id
15468       513           1    15468   841
          route_id  service_id  trip_id
15469       513           1    15469   842
          route_id  service_id  trip_id
15470       513           1    15470   843
          route_id  service_id  trip_id
15471       513           1    15471   844
          route_id  service_id  trip_id
15472       513           1    15472   845
          route_id  service_id  trip_id
15473       513           1    15473   846
          route_id  service_id  trip_id
15474       513           1    15474   847
          route_id  service_id  trip_id
15475       513           1    15475   848
          route_id  service_id  trip_id
15476       513           1    15476   849
          route_id  service_id  trip_id
15477       513           1    15477   850
          route_id  service_id  trip_id
15478       513           1    15478   851
          route_id  service_id  trip_id
15479       513           1    15479   852
          route_id  service_id  trip_id
15480       513           1    15480   853
          route_id  service_id  trip_id
15481       513           1    15481   854
          route_id  service_id  trip_id
15482       513           1    15482   855
          route_id  service_id  trip_id
15483       513           1    15483   856
          route_id  service_id  trip_id
15484       513           1    15484   857
          route_id  service_id  trip_id
15485       513           1    15485   858
          route_id  service_id  trip_id
15486       513           1    15486   859
          route_id  service_id  trip_id
15487       513           1    15487   860
          route_id  service_id  trip_id
15488       513           1    15488   861
          route_id  service_id  trip_id
15489       513           1    15489   862
          route_id  service_id  trip_id
15490       513           1    15490   863
          route_id  service_id  trip_id
15491       513           1    15491   864
          route_id  service_id  trip_id
15492       513           1    15492   865
          route_id  service_id  trip_id
15493       513           1    15493   866
          route_id  service_id  trip_id
15494       513           1    15494   867
          route_id  service_id  trip_id
15495       513           1    15495   868
          route_id  service_id  trip_id
15496       513           1    15496   869
          route_id  service_id  trip_id
15497       513           1    15497   870
          route_id  service_id  trip_id
15498       513           1    15498   871
          route_id  service_id  trip_id
15499       513           1    15499   872
          route_id  service_id  trip_id
15500       513           1    15500   873
          route_id  service_id  trip_id
15501       513           1    15501   874
          route_id  service_id  trip_id
15502       513           1    15502   875
          route_id  service_id  trip_id
15503       513           1    15503   876
          route_id  service_id  trip_id
15504       513           1    15504   877
          route_id  service_id  trip_id
15505       513           1    15505   878
          route_id  service_id  trip_id
15506       513           1    15506   879
          route_id  service_id  trip_id
15507       513           1    15507   880
          route_id  service_id  trip_id
15508       513           1    15508   881
          route_id  service_id  trip_id
15509       513           1    15509   882
          route_id  service_id  trip_id
15510       513           1    15510   883
          route_id  service_id  trip_id
15511       513           1    15511   884
          route_id  service_id  trip_id
15512       513           1    15512   885
          route_id  service_id  trip_id
15513       513           1    15513   886
          route_id  service_id  trip_id
15514       513           1    15514   887
          route_id  service_id  trip_id
15515       513           1    15515   888
          route_id  service_id  trip_id
15516       513           1    15516   889
          route_id  service_id  trip_id
15517       513           1    15517   890
          route_id  service_id  trip_id
15518       513           1    15518   891
          route_id  service_id  trip_id
15519       513           1    15519   892
          route_id  service_id  trip_id
15520       513           1    15520   893
          route_id  service_id  trip_id
15521       513           1    15521   894
          route_id  service_id  trip_id
15522       513           1    15522   895
          route_id  service_id  trip_id
15523       513           1    15523   896
          route_id  service_id  trip_id
15524       513           1    15524   897
          route_id  service_id  trip_id
15525       513           1    15525   898
          route_id  service_id  trip_id
15526       513           1    15526   899
          route_id  service_id  trip_id
15527       513           1    15527   900
          route_id  service_id  trip_id
15617       518           1    15617   901
          route_id  service_id  trip_id
15618       518           1    15618   902
          route_id  service_id  trip_id
15619       518           1    15619   903
          route_id  service_id  trip_id
15620       518           1    15620   904
          route_id  service_id  trip_id
15621       518           1    15621   905
          route_id  service_id  trip_id
15622       518           1    15622   906
          route_id  service_id  trip_id
15623       518           1    15623   907

In [19]:
step3

       route_id  service_id  trip_id
1120         34           1     1120
1121         34           1     1121
1122         34           1     1122
1123         34           1     1123
1124         34           1     1124
1125         34           1     1125
1126         34           1     1126
1127         34           1     1127
1128         34           1     1128
1129         34           1     1129
1130         34           1     1130
1131         34           1     1131
1132         34           1     1132
1133         34           1     1133
1134         34           1     1134
1135         34           1     1135
1136         34           1     1136
1137         34           1     1137
1138         34           1     1138
1139         34           1     1139
1140         34           1     1140
1141         34           1     1141
1142         34           1     1142
1143         34           1     1143
1144         34           1     1144
1145         34           1     1145
1146         34           1     1146
1147         34           1     1147
1148         34           1     1148
1149         34           1     1149
...         ...         ...      ...
15505       513           1    15505
15506       513           1    15506
15507       513           1    15507
15508       513           1    15508
15509       513           1    15509
15510       513           1    15510
15511       513           1    15511
15512       513           1    15512
15513       513           1    15513
15514       513           1    15514
15515       513           1    15515
15516       513           1    15516
15517       513           1    15517
15518       513           1    15518
15519       513           1    15519
15520       513           1    15520
15521       513           1    15521
15522       513           1    15522
15523       513           1    15523
15524       513           1    15524
15525       513           1    15525
15526       513           1    15526
15527       513           1    15527
15617       518           1    15617
15618       518           1    15618
15619       518           1    15619
15620       518           1    15620
15621       518           1    15621
15622       518           1    15622
15623       518           1    15623

[908 rows x 3 columns]

In [20]:
to_comp = np.unique(np.asarray(step3['route_id']))
step4 = pd.DataFrame()
for rid in to_comp:
    c = routes.loc[routes['route_id'] ==rid]
    step4 = step4.append(c)

In [21]:
step4

     route_short_name route_long_name  route_type  route_id
34                NaN        206ADown           3        34
36                NaN         211DOWN           3        36
69                NaN           723Up           3        69
168               NaN           534UP           3       168
179               NaN        GL23Down           3       179
200               NaN        740ExtUP           3       200
448               NaN      73LnkSTLUp           3       448
450               NaN            85UP           3       450
458               NaN           143UP           3       458
476               NaN            73UP           3       476
480               NaN         85ExtUp           3       480
482               NaN           88AUp           3       482
513               NaN      624ACLDown           3       513
518               NaN    624BLnkSTLUp           3       518

In [22]:
source_route_id = np.asarray(step4['route_id'])

In [23]:
## 1120-1154

In [24]:
qw=pd.DataFrame()
for i in range(1120,1155):
    tr = stop_times.loc[stop_times['trip_id']==i]
    qw=qw.append(tr)

In [25]:
vikaspuri-nsp

NameError: name 'vikaspuri' is not defined

In [ ]:
q = find_zero_hop('Preet Vihar') 
w = find_zero_hop('Welcome Metro Station')

In [ ]:
q[1]

In [ ]:
w[1]

In [26]:
bus_from_one = find_route_ids('Hasanpur Depot')[1]

In [27]:
step_1_1=pd.DataFrame()
for i in bus_from_one:
    step_1_1 = step_1_1.append(routes.loc[routes['route_long_name'] == i])

In [28]:
step_1_2 = pd.DataFrame()

for i in np.asarray(step_1_1['route_id']):
    print("       ",i)
    step_1_2 = step_1_2.append(trips.loc[trips['trip_id']==i])

        34
        36
        69
        168
        179
        200
        448
        450
        458
        476
        480
        482
        513
        518

In [29]:
np.asarray(step_1_2['trip_id'])

array([ 34,  36,  69, 168, 179, 200, 448, 450, 458, 476, 480, 482, 513,
       518])

In [30]:
step_1_3= pd.DataFrame()
for i in np.asarray(step_1_2['trip_id']):
    step_1_3 = step_1_3.append(stop_times.loc[stop_times['trip_id']==i])

In [31]:
step_1_3

       trip_id arrival_time departure_time  stop_id  stop_sequence
1496        34     19:08:00       19:08:00     2270              0
1497        34     19:09:52       19:09:52      978              1
1498        34     19:12:17       19:12:17     3005              2
1499        34     19:14:02       19:14:02      255              3
1500        34     19:16:47       19:16:47     3074              4
1501        34     19:19:32       19:19:32      764              5
1502        34     19:22:49       19:22:49      619              6
1503        34     19:24:22       19:24:22     1973              7
1504        34     19:27:54       19:27:54     2502              8
1505        34     19:34:25       19:34:25     2871              9
1506        34     19:37:29       19:37:29     3039             10
1507        34     19:40:53       19:40:53     1462             11
1508        34     19:44:01       19:44:01      731             12
1509        34     19:46:04       19:46:04     1837             13
1510        34     19:48:15       19:48:15     3585             14
1511        34     19:52:08       19:52:08     3425             15
1512        34     19:56:17       19:56:17     3227             16
1513        34     19:59:23       19:59:23      949             17
1514        34     20:02:13       20:02:13      953             18
1515        34     20:05:45       20:05:45     3092             19
1516        34     20:07:35       20:07:35      803             20
1517        34     20:10:30       20:10:30     1416             21
1518        34     20:12:20       20:12:20     2768             22
1519        34     20:14:13       20:14:13     3034             23
1520        34     20:15:59       20:15:59      733             24
1521        34     20:17:20       20:17:20      703             25
1522        34     20:22:11       20:22:11      580             26
1523        34     20:26:37       20:26:37     3156             27
1524        34     20:27:33       20:27:33     2142             28
1525        34     20:29:05       20:29:05     3451             29
...        ...          ...            ...      ...            ...
18151      513     19:49:50       19:49:50     1646             25
18152      513     19:52:47       19:52:47      328             26
18153      513     19:58:41       19:58:41     1811             27
18262      518     20:02:00       20:02:00     2087              0
18263      518     20:04:31       20:04:31     3422              1
18264      518     20:07:10       20:07:10     1225              2
18265      518     20:10:45       20:10:45     2433              3
18266      518     20:12:18       20:12:18      536              4
18267      518     20:14:03       20:14:03      440              5
18268      518     20:15:08       20:15:08       57              6
18269      518     20:20:06       20:20:06     2604              7
18270      518     20:22:23       20:22:23     3585              8
18271      518     20:26:16       20:26:16     3425              9
18272      518     20:27:23       20:27:23     1024             10
18273      518     20:30:25       20:30:25     3227             11
18274      518     20:33:31       20:33:31      949             12
18275      518     20:38:17       20:38:17      583             13
18276      518     20:40:44       20:40:44     2105             14
18277      518     20:44:17       20:44:17     1309             15
18278      518     20:46:22       20:46:22     3374             16
18279      518     20:48:49       20:48:49     3088             17
18280      518     20:52:45       20:52:45      404             18
18281      518     20:53:18       20:53:18     3214             19
18282      518     20:59:55       20:59:55     2373             20
18283      518     21:03:43       21:03:43     2309             21
18284      518     21:10:04       21:10:04     1978             23
18285      518     21:12:20       21:12:20     3506             24
18286      518     21:13:50       21:13:50     1646             25
18287      518     21:16:47       21:16:47      328             26
18288      518     21:22:41       21:22:41     1811             27

[446 rows x 5 columns]

In [32]:
step_1_4 = pd.DataFrame()
for i in np.asarray(step_1_3['stop_id']):
    step_1_4 = step_1_4.append(stops.loc[stops['stop_id']==i])

In [33]:
step_1_4

,stop_id,stop_code,stop_name,stop_lat,stop_lon
2207,2270,U01056,Hari Nagar Clock Tower,28.625200,77.110800
966,978,U01053,DDU Hospital,28.628000,77.110700
2906,3005,U01063,Beriwala Bagh,28.631450,77.111967
255,255,U01082,Swarg Ashram,28.631000,77.114900
2969,3074,U01122,LIG Flats,28.630900,77.119600
758,764,DC3909,Hari Nagar (Mohan Mandir) Mayapuri,28.630683,77.124267
616,619,U01217,Government Press,28.634617,77.127633
1922,1973,U99823,Mayapuri Depot,28.636850,77.128350
2430,2502,U01326,Wood Market,28.639300,77.133700
2777,2871,U01414,PS Kirti Nagar,28.646715,77.140900
2936,3039,U01381,F Block Kirti Nagar,28.651300,77.140900
1433,1462,U01335,Kirti Nagar,28.654783,77.136667
725,731,U01389,Moti Nagar Market,28.657233,77.141250
1794,1837,U01425,Moti Nagar,28.658867,77.144183
3449,3585,U01462,ESI Dispensary/CGHS Dispensary,28.660583,77.147367
3301,3425,U01525,Campa Cola,28.662800,77.153500
3117,3227,U01601,DCM Chemical,28.665367,77.159933
938,949,U01640,Zakhira,28.668000,77.164283
942,953,U01697,Inderlok,28.671400,77.167200
2987,3092,U01788,Shastri Nagar Shiv Mandir,28.671700,77.173200
797,803,U01834,Shastri Nagar E Block,28.671267,77.176283
1390,1416,U01902,Shastri Nagar Metro Station,28.670231,77.181136
2678,2768,U01940,Subhadra Colony,28.671200,77.184050
2932,3034,U01999,Shastri Nagar A Block,28.673050,77.186467
727,733,U02023,Gulabi Bagh,28.674998,77.188525
697,703,U02036,Chowki No 2 / Gulabi Bagh Crossing,28.676983,77.188900
578,580,U02136,Shakti Nagar Nangia Park,28.680350,77.196233
3050,3156,U02252,Roop Nagar / Kamla Nagar,28.684283,77.202317
2087,2142,U02286,Police Station Roop Nagar / Banglow Road,28.684821,77.203792
3324,3451,U02336,Maurice Nagar II,28.686500,77.205567
...,...,...,...,...,...
1611,1646,U01655,Ashok Vihar Xing,28.702100,77.164350
328,328,U01720,Shalimar Bagh(Ring Road),28.703733,77.169017
1768,1811,U01851,Azadpur Terminal,28.707200,77.178300
2033,2087,U01458IP,Inderpuri Krishi Kunj,28.637749,77.146347
3298,3422,U01436,Loha Mandi,28.641383,77.145217
1206,1225,U01494,Bentax,28.644717,77.147667
2365,2433,U01466,Naraina Depot,28.649050,77.151300
534,536,U01520,Pandav Nagar,28.650051,77.153678
439,440,U01549,Shadipur Colony,28.651600,77.156100
57,57,U01543,Shadipur Depot,28.653117,77.155500
2527,2604,U01472,Moti Nagar Industrial Area,28.657317,77.148500
3449,3585,U01462,ESI Dispensary/CGHS Dispensary,28.660583,77.147367
3301,3425,U01525,Campa Cola,28.662800,77.153500
1010,1024,U01544,Swatantra Bharat Mills,28.663528,77.155197
3117,3227,U01601,DCM Chemical,28.665367,77.159933
938,949,U01640,Zakhira,28.668000,77.164283
581,583,U01561,Ram Pura (Ashok Park),28.671480,77.157173
2050,2105,U01491,Ram Pura,28.671883,77.153033
1289,1309,U01459,Power House,28.672702,77.147024
3251,3374,U01417,Punjabi Bagh Terminal (Rohtak Road),28.673150,77.143517
2983,3088,U99833A,Punjabi Bagh,28.675500,77.140300
404,404,U01402,Shakurpur Shiv Mandir,28.680921,77.142863
3104,3214,U01463,Britannia (Shakurpur),28.680300,77.142217
2307,2373,U01488,Telephone Exchange,28.686500,77.151000
2245,2309,U01521,Wazirpur Depot Ring Road,28.691796,77.153390
1927,1978,U01574,Prem Bari Pull,28.700267,77.158283
3374,3506,U01610,Shalimar Bagh,28.701283,77.161967
1611,1646,U01655,Ashok Vihar Xing,28.702100,77.164350
328,328,U01720,Shalimar Bagh(Ring Road),28.703733,77.169017
1768,1811,U01851,Azadpur Terminal,28.707200,77.178300

In [63]:
def find_one_hop(name):
    
    bus_from_one = find_route_ids(name)[1]
    print(bus_from_one)
    step_1_1=pd.DataFrame()
    for i in bus_from_one:
        step_1_1 = step_1_1.append(routes.loc[routes['route_long_name'] == i])

    step_1_2 = pd.DataFrame()

    for i in np.asarray(step_1_1['route_id']):
        step_1_2 = step_1_2.append(trips.loc[trips['trip_id']==i])

    step_1_3= pd.DataFrame()
    for i in np.asarray(step_1_2['trip_id']):
        step_1_3 = step_1_3.append(stop_times.loc[stop_times['trip_id']==i])

    step_1_4 = pd.DataFrame()
    for i in np.asarray(step_1_3['stop_id']):
        step_1_4 = step_1_4.append(stops.loc[stops['stop_id']==i])
        
    return step_1_4

In [64]:
a = find_one_hop('C Block Vikaspuri')
b = find_one_hop('Hasanpur Depot')

['883ExtUp' '883UP' '871DOWN']
['206ADown' '211DOWN' '723Up' '534UP' 'GL23Down' '740ExtUP' '73LnkSTLUp'
 '85UP' '143UP' '73UP' '85ExtUp' '88AUp' '624ACLDown' '624BLnkSTLUp']

In [65]:
a = np.asarray(a['stop_name'])
b = np.asarray(b['stop_name'])

In [66]:
set(a).intersection(set(b))

{'Ashok Vihar Xing',
 'Azadpur Terminal',
 'Balak Ram Hospital',
 'Banarsi Daas Estate Timarpur',
 'Bentax',
 'Beriwala Bagh',
 'Britannia (Shakurpur)',
 'Campa Cola',
 'Chowki No 2 / Gulabi Bagh Crossing',
 'DCM Chemical',
 'DDA Flats Hari Nagar',
 'DDU Hospital',
 'ESI Dispensary',
 'ESI Dispensary/CGHS Dispensary',
 'F Block Kirti Nagar',
 'Government Press',
 'Gulabi Bagh',
 'Hari Nagar Clock Tower',
 'INS Hostel',
 'Inderlok',
 'Inderlok Metro Station',
 'Inderpuri Krishi Kunj',
 'Kamla Nagar/ Roop Nagar',
 'Khalsa College',
 'Kirti Nagar',
 'Loha Mandi',
 'Mall Road',
 'Maurice Nagar II',
 'Mayapuri Depot',
 'Metal Forging',
 'Moti Nagar',
 'Moti Nagar Industrial Area',
 'Naraina Depot',
 'Nehru Vihar',
 'Nehru Vihar Xing',
 'PS Kirti Nagar',
 'Pandav Nagar',
 'Patel Chest',
 'Police Station Timarpur',
 'Power House',
 'Prem Bari Pull',
 'Punjabi Bagh',
 'Punjabi Bagh Terminal (Rohtak Road)',
 'Ram Pura',
 'Ram Pura (Ashok Park)',
 'Shadipur Colony',
 'Shadipur Depot',
 'Shakti Nagar Nangia Park',
 'Shakurpur Shiv Mandir',
 'Shalimar Bagh',
 'Shalimar Bagh(Ring Road)',
 'Shastri Nagar A Block',
 'Shastri Nagar E Block',
 'Shastri Nagar Metro Station',
 'Shastri Nagar Shiv Mandir',
 'Shri Ram College',
 'Subhadra Colony',
 'Swarg Ashram',
 'Swatantra Bharat Mills',
 'Telephone Exchange',
 'Timarpur',
 'Vishwa Vidyalaya Metro Station',
 'Wazirpur Depot Ring Road',
 'Wood Market (Mansarovar Garden)',
 'Zakhira'}

In [68]:
check_zero_hop('Zakhira', 'C Block Vikaspuri')

False